---
title: "Домашнее задание №2"
output: html_document
---

# Домашнее задание № 2
## Основы исследовательского анализа данных.
## Требования к оформлению
* Оформить решение в R Markdown. 
* Сохранить файл в свой репозиторий.
* Выгрузить R Markdown в HTML, назвать своим именем и отправить по почте (если хочется сдать раньше или нужна помощь).

## Исходные данные

По адресу https://raw.githubusercontent.com/SergeyMirvoda/da2016/master/data/calif_penn_2011.csv можно получить набор данных, 
содержащий информацию о домовладениях в Калифорнии и Пенсильвании за 2011г. Информация сгруппированна по зонам переписи ([Census tracts](https://en.wikipedia.org/wiki/Census_tract)).

>В построении диаграмм может помочь книга [The R Cookbook](http://shop.oreilly.com/product/9780596809164.do). Рецепты 10.1 и 10.2.

### Загрузка и очистка данных
- Загрузите данные в датафрейм, который назовите ``data``.
- Сколько строк и столбцов в ``data``?
- Выполните следующую команду и объясните, что она делает.
```colSums(apply(data,c(1,2), is.na))```
- Функция ``na.omit()`` принимает датафрейм и возвращает новый датафрейм, игнорируя строки, содержащие
значение _NA_. Используйте эту функцию для удаления строк с неполными данными.
- Сколько строк было удалено?
- Соответствует ли результат выполнения, значениям из пункта 3?
```
library(tidyverse)
data <- read.csv("https://raw.githubusercontent.com/SergeyMirvoda/da2016/master/data/calif_penn_2011.csv", stringsAsFactors = FALSE)
nCols <- data %>% length()      #34
nRows <-data[[1]] %>% length()  #11275
colSums(apply(data,c(1,2), is.na))  #проверяем, сколько существует строк, у которых в первых двух столбцах присутсвуют NA значения
data <- data %>% na.omit()
rowsOmitted <- nRows - data[[1]] %>% length() #670
```


### Новые дома
* Переменная(колонка) _Built_2005_or_later_ содержит данные о проценте домов, построенных с 2005 года. Постройте диаграмму рассеяния (scatterplot)
медианы стоимости домов (переменная _Median_house_value_) относительно процента новых домов.
* Постройте ещё два графика для каждого из штатов отдельно. Номер штата содержится в переменной (_STATEFP_), где Калифорния 6-й штат, а Пенсильвания 42.
```
data %>%
ggplot(aes(Median_house_value, Built_2005_or_later)) +
scatterplot()
# Графики для Калифорнии и Пенсильвании
data %>%
group_by(STATEFP) %>% 
ggplot(aes(Built_2005_or_later, Median_house_value, color = STATEFP)) + geom_point()
```

### Незанятые дома
Уровень найма (vacancy rate) — доля домов, которые не были заняты. В данных содержатся колонки,
содержащие общее количество домовладений и количество не занятых домовладений.

* В датафрейм _data_ добавьте новую колонку _vacancy_rate_, которая должна содержать вышеописанный показатель.
* Найдите минимум, максимум, среднее и медиану полученных значений показателя. 
* Постройте диаграмму уровня найма относительно медианы стоимости домов. Что можно заметить?

```
data <- data %>% 
mutate(vacancy_rate = Vacant_units/Total_units)
maxVR <- max(data$vacancy_rate) #0.965
minVR <- min(data$vacancy_rate) #0
meanVR <- mean(data$vacancy_rate) #0.0888
medianVR <- median(data$vacancy_rate) #0.06767
data %>% 
ggplot(aes(Median_house_value, vacancy_rate)) +
geom_point()
```
Чем выше медианная стоимость дома, тем меньше доля незанятых мест.

### Корреляция
Колонка _COUNTYFP_ содержит числовой код округа внутри штата. Нас интересуют Butte County (округ 7 в Калифорнии), Santa Clara (округ 85 в Калифорнии) 
и York County (округ 133 в Пенсильвании).

* Объясните, что делает приведённый в конце задания код и как именно он это делает.
* Напишите другим способом в одну строку, то же самое, что делает нижеуказанный код. Способов получить тот же ответ множество, достаточно одного.
* Найдите средний процент построенных домовладений в округах (Butte County, Santa Clara, York County)
* Функция ``cor`` рассчитывает коэффициент корреляции между двумя переменными. Рассчитайте корреляцию между
медианы стоимости домовладений (_Median_house_value_) и процентом построенных домов (_Built_2005_or_later_):

    1. для всего набора данных
    2. для Калифорнии
    3. для Пенсильвании
    4. для округа Butte County
    5. для округа Santa Clara
    6. для округа York County

* Постройте три диаграммы медианы стоимости домовладений (_Median_house_value_) относительно медианы дохода (_Median_household_income_) 
для трёх округов. Допустимо указать все три на одном графике.

#### Код
Данный фрагмент кода находит медиану медианной стоимости домов в Калифорнии, округ №1. Во фрагменте создаётся пустая коллекция, в которую затем в теле цикла после прохождения нужных проверок добавляются новые элементы - записи из исходного дата-фрейма. После фильтрации исходных наблюдений в ещё одном цикле осуществляется проход по только что созданной коллекции и в другую коллекцию добавляются уже значения конкретно поля Median_house_value. В конце вычисляется медиана полученной коллекции.
```
acc <- c()
for (tract in 1:nrow(data)) {
  if (data$STATEFP[tract] == 6) {
    if (data$COUNTYFP[tract] == 1) {
      acc <- c(acc, tract)
    }
  }
}
accmv <- c()
for (tract in acc) {
  accmv <- c(accmv, data[tract,10])
}
median(accmv)
```

#### Код получше
```
betterWay <- data %>% 
filter(STATEFP == 6, COUNTYFP == 1) %>% 
summarise(median = median(Median_house_value)) %>%
as.double()         #474050
avgBC <- data %>%
filter(STATEFP == 6, COUNTYFP == 7) %>%
summarise(mean(Built_2005_or_later)) %>%
as.double()         #4.7
avgSC <- data %>%
filter(STATEFP == 6, COUNTYFP == 85) %>%
summarise(mean(Built_2005_or_later)) %>%
as.double()         #3.2
avgYC <- data %>%
filter(STATEFP == 42, COUNTYFP == 133) %>%
summarise(mean(Built_2005_or_later)) %>%
as.double()         #4.42
corAll <- data %>%
summarise(cor(Median_house_value, Built_2005_or_later)) %>%
as.double()         #-0.1
corCali <- data %>%
filter(STATEFP == 6) %>% 
summarise(cor(Median_house_value, Built_2005_or_later)) %>%
as.double()         #-0.11
corPens <- data %>%
filter(STATEFP == 42) %>% 
summarise(cor(Median_house_value, Built_2005_or_later)) %>%
as.double()         #0.27
corBC <- data %>%
filter(STATEFP == 6, COUNTYFP == 7) %>% 
summarise(cor(Median_house_value, Built_2005_or_later)) %>%
as.double()         #0.04
corSC <- data %>%
filter(STATEFP == 6, COUNTYFP == 85) %>% 
summarise(cor(Median_house_value, Built_2005_or_later)) %>%
as.double()         #-0.17
corYC <- data %>%
filter(STATEFP == 42, COUNTYFP == 133) %>% 
summarise(cor(Median_house_value, Built_2005_or_later)) %>%
as.double()         #0.39
data %>% 
filter(COUNTYFP %in% c(7, 85, 133)) %>% 
ggplot(aes(Median_household_income, Median_house_value, color = COUNTYFP)) +
geom_point()
```
endline.
